const tg=window.Telegram?.WebApp;tg?.ready();const initData=tg?.initData||"";const headers={"Content-Type":"application/json","X-Telegram-Init-Data":initData};const $=id=>document.getElementById(id);
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers,...opts.headers}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||"Request failed");return d}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function summary(){const d=await api("/api/admin/summary");$("users").textContent=d.users;$("tasksCount").textContent=d.tasks;$("withdrawCount").textContent=d.pending_withdrawals;$("completionCount").textContent=d.pending_completions}
async function completions(){const a=await api("/api/admin/completions");$("completions").innerHTML=a.length?a.map(x=>`<div class="item"><b>Completion #${x.id}</b><small>User DB ID: ${x.user_id} · Task ID: ${x.task_id}</small><p>${esc(x.proof||"No proof submitted")}</p><button data-review-task="${x.id}" data-action="approve">Approve & credit</button><button class="secondary" data-review-task="${x.id}" data-action="reject">Reject</button></div>`).join(""):"<p>No pending completions.</p>"}
async function withdrawals(){const a=await api("/api/admin/withdrawals");$("withdrawals").innerHTML=a.length?a.map(x=>`<div class="item"><b>Withdrawal #${x.id} — $${Number(x.amount_usd).toFixed(4)}</b><small>User DB ID: ${x.user_id} · ${esc(x.method)} · ${esc(x.payout_details)}</small><button data-review-withdraw="${x.id}" data-action="approve">Mark paid / approve</button><button class="secondary" data-review-withdraw="${x.id}" data-action="reject">Reject & refund</button></div>`).join(""):"<p>No pending withdrawals.</p>"}
async function users(){const a=await api("/api/admin/users");$("userList").innerHTML=a.map(x=>`<div class="item"><b>${esc(x.username||"No username")} — $${Number(x.balance_usd).toFixed(4)}</b><small>Telegram ID: ${x.telegram_id} · DB ID: ${x.id} · ${x.blocked?"Blocked":"Active"}</small></div>`).join("")||"<p>No users.</p>"}
$("taskForm").addEventListener("submit",async e=>{e.preventDefault();try{const d=await api("/api/admin/tasks",{method:"POST",body:JSON.stringify({title:$("title").value,description:$("description").value,category:$("category").value,reward_usd:$("reward").value,target_url:$("url").value||null,verification_mode:"manual",active:true})});$("taskMsg").textContent="Created task #"+d.id;e.target.reset();await summary()}catch(err){$("taskMsg").textContent=err.message}});
document.body.addEventListener("click",async e=>{const t=e.target.closest("[data-review-task]");const w=e.target.closest("[data-review-withdraw]");try{if(t){await api(`/api/admin/completions/${t.dataset.reviewTask}/review`,{method:"POST",body:JSON.stringify({action:t.dataset.action,note:"Reviewed in admin panel"})});await completions();await summary()}if(w){await api(`/api/admin/withdrawals/${w.dataset.reviewWithdraw}/review`,{method:"POST",body:JSON.stringify({action:w.dataset.action,note:"Reviewed in admin panel"})});await withdrawals();await summary()}}catch(err){alert(err.message)}});
$("refreshCompletions").onclick=()=>completions().catch(e=>alert(e.message));$("refreshWithdrawals").onclick=()=>withdrawals().catch(e=>alert(e.message));$("refreshUsers").onclick=()=>users().catch(e=>alert(e.message));
(async()=>{if(!initData){alert("Open Admin Panel from Telegram Mini App so Telegram identity can be verified.");return}try{await summary();await completions();await withdrawals();await users()}catch(e){alert(e.message)}})();
